[package]
name = "spotify-rolling-100"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
awc = "3.5.1"
dotenv = "0.15.0"
env_logger = "0.11.5"
http = "1.2.0"
once_cell = "1.20.2"
rand = "0.8.5"
serde = { version = "1.0.216", features = ["derive"] }
url = "2.5.4"
